project_id = "hknphfqeoegsxdlgyrae"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
enable_signup = true

[functions.upload-file]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = true

[functions.export-data]
verify_jwt = true

[functions.template-editor]
verify_jwt = true

[functions.approval-workflow]
verify_jwt = true

[functions.realtime-analytics]
verify_jwt = true

[functions.ai-analytics]
verify_jwt = true