// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsrcdzvzxallqdeocxfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcmNkenZ6eGFsbHFkZW9jeGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDk3OTYsImV4cCI6MjA2NTU4NTc5Nn0.Jf-1qsTBiC68PDvwzd2-ytKEw6uSJDUPfRRjsUR-Wgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);