// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hknphfqeoegsxdlgyrae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrbnBoZnFlb2Vnc3hkbGd5cmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTc3NzMsImV4cCI6MjA2NTQzMzc3M30.0K_5wMAzYevUasuPTDlQI9IfdB77js8-1aJAqQuPg6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);